apiVersion: v1
kind: Service
metadata:
  name: guin-mono-app
  labels:
    app: webapp
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guin-mono-rs
spec:
  replicas: 3

  selector:
    matchLabels:
      app: webapp
      tier: app
  template:
    metadata:
      labels:
        app: webapp
        tier: app
    spec:
      containers:
        - name: 9in-mono
          image: 9in-mono:test
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
