version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-db
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    command:
      - --character-set-client-handshake=utf8mb4
