version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-db
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      TZ: "Asia/Seoul"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci # 한글안깨지게 character set utf-8 설정

  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=test
    ports:
      - "6379:6379"
