spring:
  datasource:
    url: jdbc:mysql://localhost:3309/testdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
