name: Deploy on Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_URL }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_ID }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            cd Backend/
            sudo docker-compose down
            cd ..
            rm -rf Backend/
            git clone https://github.com/9in-team/Backend.git
            cd Backend/
            sudo docker-compose up -d
            ./gradlew build
            ./gradlew bootRun
            